### ISSUE TITLE
Modify URL by stripping query parameters

### ISSUE THREAD

**Issue by bosonno** [joeferner/node-http-mitm-proxy#103]
How can I strip the URL query parameters before sending the ctx.proxyToServerRequest.url?

**Comment by bosonno** [comment]
From https://github.com/joeferner/node-http-mitm-proxy/issues/72

proxy.onRequest(function(ctx, callback) {
  if (ctx.clientToProxyRequest.headers.host == 'www.youdomain.com'
    && ctx.clientToProxyRequest.url.indexOf('/base/url/to/intercept') == 0) {
    ctx.proxyToServerRequestOptions.host = 'www.overridehost.com';
    ctx.proxyToServerRequestOptions.path = '/override/url';
  }
  return callback();
});

**Comment by mk-pmb** [comment]
Did the example code solve your problem? If so, please close the issue.
