### ISSUE TITLE
Upstream proxy

### ISSUE THREAD

**Issue by Programming4life** [joeferner/node-http-mitm-proxy#104]
How can I add an upstream proxy, or how can I set the http agent so that it'll use the upstream proxy?

**Comment by felicienfrancois** [comment]
To support upstream proxy you can set a custom agent in either

- [proxy.listen options](https://github.com/joeferner/node-http-mitm-proxy#proxylisten) `httpAgent` and `httpsAgent`
- in `ctx.proxyToServerRequestOptions.agent` at each requests ([onRequest](https://github.com/joeferner/node-http-mitm-proxy#proxyonrequestfn-or-ctxonrequestfn))
