### ISSUE TITLE
Changing agent proxy on working proxy server

### ISSUE THREAD

**Issue by d0c3ntOS** [joeferner/node-http-mitm-proxy#106]
I have couple of proxy around the world. I want change proxy when I know URL of request. 

I use "https-proxy-agent" - https://www.npmjs.com/package/https-proxy-agent

I try change proxy.httpsAgent, closed server (proxy.close()) and strart again (proxy.listen({....})) my proxy server but this method don't work. 

------------------------

```
proxy.onRequest(function(ctx, callback) {
    ctx.use(Proxy.gunzip);

    console.log("--URL:",ctx.clientToProxyRequest.url);
    dbLib.getProxy(ctx.clientToProxyRequest.url, function() {
        if (global.proxy.length > 5){
            proxy.close();
            myproxy = process.env.http_proxy || 'http://'+global.proxy+':3128';
            myAgent = new HttpsProxyAgent(myproxy);
            proxy.httpsAgent = myAgent;
            proxy.httpAgent = myAgent;
            proxy.listen({port: 8800,  forceSNI: true});
            proxy.httpsAgent = myAgent;
            proxy.httpAgent = myAgent;
        }
    });
```

**Comment by felicienfrancois** [comment]
You can set the http agent on the fly using
```javascript
proxy.onRequest(function(ctx, callback) {
  ctx.proxyToServerRequestOptions.agent = myAgent,
  return callback();
});
// and for websockets
proxy.onWebSocketConnection(function(ctx, callback) {
  ctx.proxyToServerWebSocketOptions.agent = myAgent,
  return callback();
});
```

**Comment by d0c3ntOS** [comment]
Thank you for your quick answer, but it did not help :(

![001](https://cloud.githubusercontent.com/assets/25740181/22982910/bf6a1d6e-f3a0-11e6-8e07-ee87168b1e20.jpg)

when I reload the page everything is ok ...
... but I want to change gateway of connection before I make the first connection ...

![002](https://cloud.githubusercontent.com/assets/25740181/22982956/e60199f2-f3a0-11e6-8ea6-aa65a609dcf8.jpg)

**Comment by d0c3ntOS** [comment]
I think library establish connection before I change Agent, and use them. I don't now how to kill all old connections (old = connections makes before I change Agent) , established new and use it on existing context

**Comment by felicienfrancois** [comment]
Don't close and relaunch the proxy at each request, it cannot work.

Do something like that:

```
proxy.onRequest(function(ctx, callback) {
    ctx.use(Proxy.gunzip);
    console.log("--URL:",ctx.clientToProxyRequest.url);
    dbLib.getProxy(ctx.clientToProxyRequest.url, function() {
        if (global.proxy.length > 5){
            proxy.close();
            myproxy = process.env.http_proxy || 'http://'+global.proxy+':3128';
            myAgent = new HttpsProxyAgent(myproxy);
            ctx.proxyToServerRequestOptions.agent = myAgent;
        }
        callback(); // call the onRequest callback after changing agent
   });
});
proxy.listen({port: 8800,  forceSNI: true}); // listen outside the onRequest event
```

**Comment by d0c3ntOS** [comment]
Everything works ok. Thank you very much. I had problem with sync in javascript.
