### ISSUE TITLE
0.5.2 breaks ajax requests

### ISSUE THREAD

**Issue by stevejhiggs** [joeferner/node-http-mitm-proxy#111]
after upgrading to 0.5.2 any ajax requests inside the proxy end up redirecting the top level page, breaking the site.

**Comment by joeferner** [comment]
Strange, ajax requests shouldn't be any different then normal requests. Can you give any more details?

**Comment by stevejhiggs** [comment]
sorry, I know I didn't leave much in the way of details. I'm just trying to create a simple reproduction case

**Comment by stevejhiggs** [comment]
Still working on a repo that's not tied into all our other systems.

Interestingly though by bisecting the issue I've found its caused by 

https://github.com/joeferner/node-http-mitm-proxy/commit/d3d24e75f535e3c6125d738a46d68c77abf08aa2

**Comment by stevejhiggs** [comment]
Ok steps to reproduce:

- run http-mitm-proxy 0.5.2 locally and set up chrome to use it (may need to use --ignore-certificate-errors as args to chrome to work around cert errors).
- visit https://www.prettylittlething.com/robynn-black-fluffy-sliders.html and click 'add to basket'
- Site will display a request error

If you then revert https://github.com/joeferner/node-http-mitm-proxy/commit/d3d24e75f535e3c6125d738a46d68c77abf08aa2 and try again you will see everything is fine.

Currently no idea why removing the content-length header causes stuff to break though.

**Comment by joeferner** [comment]
Any thoughts on this @rastapasta ?  This is pretty weird because I agree content length should be removed because the response will be sent back chunked which doesn't require a content length.

**Comment by stevejhiggs** [comment]
aha I wonder if its the same as https://github.com/elazarl/goproxy/issues/11

I'll check to see if not doing this for head requests fixes the issue

**Comment by stevejhiggs** [comment]
nope, its a post request thats failing

**Comment by jasonswearingen** [comment]
@stevejhiggs and @joeferner  according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding I think this is the correct solution:

```
if(headers["transfer-encoding"]==="chunked"){
  delete headers['content-length'];
}
```

**Comment by stevejhiggs** [comment]
yep, looks right to me

**Comment by stevejhiggs** [comment]
Tested in new version and the issue is now resolved
