### ISSUE TITLE
How do I set the host/interface to list on?

### ISSUE THREAD

**Issue by iffy** [joeferner/node-http-mitm-proxy#112]
I see that `port` is an option to `listen()` but I don't find a way to choose which interface (`0.0.0.0` or `localhost` or my ip) to listen on.

**Comment by joeferner** [comment]
Done https://github.com/joeferner/node-http-mitm-proxy/commit/706f1199e30319bf34b5dbd95271361d17c13772

**Comment by iffy** [comment]
Thanks!

**Comment by wisec** [comment]
@joeferner when do you plan to release this fix on an official npm version?
Thanks and keep up!
