### ISSUE TITLE
how to use a global wildcard cert? (avoid creating certs for each domain)

### ISSUE THREAD

**Issue by jasonswearingen** [joeferner/node-http-mitm-proxy#113]
it looks like mitm-proxy creates new certs for each domain.  is there some way to create a single global wildcard cert and use that?

**Comment by joeferner** [comment]
Not that I can see. There is something called a "Multiple Domain (UCC) SSL certificate" but I can't find much info on them.

**Comment by jasonswearingen** [comment]
is there a way to not resign the page? I am hoping that my browser (phantomjs) will still let the page since  I disabled cert validation.

**Comment by jasonswearingen** [comment]
hi, I got it working, maybe @joeferner you can integrate this idea into your library to make it faster and take less memory.

Here's what I did: 

I tried making my own global wildcard certificate   (when generating a self-signed cert, just use "*" as the FQDN) and then I load this cert in the ```onCertificateMissing``` function:

```
//load our global wildcard keyfiles
	const globKeyData = slib.file.fsPromise.readFileSync(__dirname + "/../global-wildcard.key", "utf8");
	const globCertData = slib.file.fsPromise.readFileSync(__dirname + "/../global-wildcard.crt", "utf8");
	proxy.onCertificateMissing = function (ctx, files, callback) {
		log.warn('Looking for "%s" certificates', ctx.hostname);
		console.log('"%s" missing', ctx.files.keyFile);
		console.log('"%s" missing', ctx.files.certFile);

		return callback(null, {
			keyFileData: globKeyData,
			certFileData: globCertData,
			hosts:["*"],
		});
};
```

it works.     FYI it looks like the ```onCertificateRequired``` is never called, and the ```hosts``` parameter of the ```onCertificateMissing``` callback doesn't seem to do anything.  (other domains still ask for requests)

If you do this (a single wildcard cert) you can remove all the code on creating a fake root CA and all the leaf certs.
