### ISSUE TITLE
Get entire request and response

### ISSUE THREAD

**Issue by stefanocoding** [joeferner/node-http-mitm-proxy#117]
This is not an issue on node-http-mitm-proxy, but maybe someone have the answer here...
I want to access the entire request made by the client and the entire response returned by the server. Example:
```
GET / HTTP/1.1
Host: www.google.com
....
....
```
and 
```
HTTP/1.1 200
...
...

this is the body
```

This is a working example to get the entire HTTP response:
```javascript
var https = require('https')
var req = https.request({host: 'google.com'})
req.on('socket', function (socket) {
  socket.on('data', function(chunk){
    console.log(chunk.toString())
  });
}).end()
```
I would like to know how to implement something similar using node-http-mitm-proxy. I've been reading _proxy.js_ and figured out that I can do this:
```javascript
ctx.serverToProxyResponse.socket.on('data', function (c) {
    console.log(c.toString())
})
```
however I'm just getting the body of the response and not the entire response as my example above.

Any hint is enough if you don't have time available to help me.
Thank you in advance.

**Comment by stefanocoding** [comment]
Seems like I'm able to do the same as the example I described adding this code:
```javascript
ctx.proxyToServerRequest.on('socket', function (skt) {
      skt.on('data', function (chnk) {
        console.log(chnk.toString())
      })
})
```
I will check if I'm able to do something to provide the 'data' from 'socket' to where I'm calling the library.

**Comment by stefanocoding** [comment]
I ended up writing my own proxy because it was better suited for my necessity. But I used the `ca.js` file from this project :)
Thanks.

**Comment by DblK** [comment]
@stefanocoding , did you have anthing to share? I have successfully retrieve all response object but I have trouble to have all request (including body) see #187 .

Any help will be appreciated.

**Comment by stefanocoding** [comment]
@DblK I abandoned that project and I deleted the code I think. Sorry :(
I don't understand your issue based on what you described in the issue. Anyway, I'm not sure I will be helpful.
