### ISSUE TITLE
HTTP/1.1 411 Length Required

### ISSUE THREAD

**Issue by wisec** [joeferner/node-http-mitm-proxy#129]
Apple.com is on Akamai (and for sure others). 
As a matter of fact it will complain about removing Content-length as comitted by  @rastapasta 
in https://github.com/joeferner/node-http-mitm-proxy/commit/d3d24e75f535e3c6125d738a46d68c77abf08aa2 

```
curl 'https://www.apple.com/search-services/suggestions/' -d '{"query":"d","src":"globalnav","id":"dda7642c-0ab7-9d73-00ed-0367d7b85ea5","locale":"en_US"}'  -ki -H 'X-Requested-By-Element: xmlhttprequest'  -H 'Content-Type: application/json'   -x '127.0.0.1:1114'
```

```
HTTP/1.1 411 Length Required
Server: AkamaiGHost
```

**Comment by joeferner** [comment]
fixed https://github.com/joeferner/node-http-mitm-proxy/commit/1eb6f7fc7a41a1961c2e3602328b9d2d734406fc
