### ISSUE TITLE
Process uncaughtException occurs on any http server error

### ISSUE THREAD

**Issue by avistramer** [joeferner/node-http-mitm-proxy#131]
Any time there is an error from the `httpServer` it causes an unhandled exception. I came across this trying to bind to an already in use port.

This library does handle the `error` event of `httpServer` correctly, however nothing is handling the `error` event of the `WebSocket.Server` instance. 

Inside the `WebSocket.Server` code it is also listening to the http server `error` event and emitting it as its own error. When nothing in the proxy handles it, an uncaught exception occurs.

Looks like `WebSocket.Server` only emits an `error` event when the underlying `httpServer` does. So seems like there are 2 possible solutions:

1. Listen to the error event on the `WebSocket.Server` instance instead of on the `httpServer` instance (to avoid duplicate error events).
2. Register an empty handler on for `self.wsServer.on('error', ...)` to avoid the uncaught exception.

Option 1 seems better? Happy to turn it into a pull request if that makes sense.

**Comment by joeferner** [comment]
I like option 1 as well. A PR would be great, thanks.
