### ISSUE TITLE
MITM with Mac

### ISSUE THREAD

**Issue by Devhercule** [joeferner/node-http-mitm-proxy#133]
Hi,

Thank you for this :)

I tested it on windows, it works perfectly, but when i package it (using Electron-Packager) and i run it on mac it does not work.

This is my error msg : 

```
Uncaught Exception:
TypeError: callback is not a function
    at /Users/admin/Desktop/.../Contents/Resources/app/mitm/proxy.js:63:14
    at /Users/admin/Desktop/.../Contents/Resources/app/mitm/ca.js:130:14
    at /Users/admin/Desktop/.../Contents/Resources/app/node_modules/async/dist/async.js:3861:9
    at /Users/admin/Desktop/Electron/.../Contents/Resources/app/node_modules/async/dist/async.js:421:16
    at iterateeCallback (/Users/admin/Desktop/Electron/.../Contents/Resources/app/node_modules/async/dist/async.js:924:17)
    at /Users/admin/Desktop/Electron/.../Contents/Resources/app/node_modules/async/dist/async.js:906:16
    at /Users/admin/Desktop/Electron/.../Contents/Resources/app/node_modules/async/dist/async.js:3858:13
    at /Users/admin/Desktop/Electron/.../Contents/Resources/app/node_modules/mkdirp/index.js:47:53
    at FSReqWrap.oncomplete (fs.js:114:15)
```

Is there any solution for this?

**Comment by felicienfrancois** [comment]
There are 2 errors in 1:

1. http-mitm-proxy failed to create the directory for storing the generated certificates
-> The default directory is in current working directory, which is probably not writable by your user in your case. You can change this directory by setting the sslCaDir options.

2. you've not passed any callback to proxy(options, callback) and as a result it failed on calling callback with the error
-> pass a callback and threat errors
We could improve this behavior by throwing the error if there is no callback here https://github.com/joeferner/node-http-mitm-proxy/blob/master/lib/proxy.js#L63.
Feel free to make a Pull Request

**Comment by Devhercule** [comment]
Thank you for your response.

For 1, you are rigth, I think thar i have no autorization to write files

For 2, on windows, the same version works perfectly, so i dont think that it is a callback call error. It's really the same version that works on windows and doesn't work on mac....

**Comment by Devhercule** [comment]
Hi @felicienfrancois,

I managed to avoid writing certificates and store them in files by removing all fs calls as you told me. I tested it on windows, it works, no certificate is saved on disk. 

But the application still always not working on MacOs.

It displays : 

```
<<<< VTVideoEncoderSelection >>>> VTSelectAndCreateVideoEncoderInstanceInternal: no video encoder found for 'avc1'

[10:22:51.406] VTSelectAndCreateVideoEncoderInstanceInternal signalled err=-12908 (err) (Video encoder not available) at /SourceCache/CoreMedia_frameworks/CoreMedia-1562.238/Sources/VideoToolbox/VTVideoEncoderSelection.c line 1245
[10:22:51.407] VTCompressionSessionCreate signalled err=-12908 (err) (Could not select and open encoder instance) at /SourceCache/CoreMedia_frameworks/CoreMedia-1562.238/Sources/VideoToolbox/VTCompressionSession.c line 946
```

And then, it displays : 

```
Request Failed.
Status Code : 504
```
PS: The same code works perfectly on windows.

Can you help me fix this issue plz

**Comment by felicienfrancois** [comment]
Hi @Devhercule, I don't think those errors are related to the proxy.
The first one may comes from electron and the second one may just be a request to an unreachable server (it could be an update check request, an error reporting, or whatever request from the webpage your browsing to with electron).

**Comment by Devhercule** [comment]
thank you
