### ISSUE TITLE
can't save certificate files on my disk

### ISSUE THREAD

**Issue by Devhercule** [joeferner/node-http-mitm-proxy#134]
Hi, 

I'm using the MITM in my Electron application.

the certifiactes files (ca.pem, private key and public key) are stored on the disk, using "sslCaDir" path.

In my case, I have not writable directories, so I'm not able to save certificate file on my disk.. How can I chage the code to have certificates on Ram and do not store them on disk. the certificates are used from RAM and deleted when the session is closed.

Is it possible with node-http-mitm-proxy

Thank you

**Comment by felicienfrancois** [comment]
As far as i know, certificates are also cached in memory (in a javascript object),
so the only thing you have to do is to catch fs errors (or event better prevent fs from loading and storing it to disk).
Removing all fs calls should work.
I you don't want to fork it, you can use it as is and either catch fs errors or mock the fs module.

**Comment by Devhercule** [comment]
I tried to remove all fs call, but that's not working

I have this error msg : `Got error: connect ECONNREFUSED 127.0.0.1:8080`

**Comment by Devhercule** [comment]
It will be in proxy.js or ca.js?

**Comment by Devhercule** [comment]
I think it's a little more complicated...

certificates, public and private keys are stored in files (.pem and .key), and then readed from these files. 

I tried to avoid storing in files, but its does not work for me

Can you tell me how can I pratically avoid to store certiificates and keys in files, and then be able to read them from variables and not from files

Thank you in advance

**Comment by 131** [comment]
I wrote an ES7 version of node-mitm (see 131/mitm-proxy) and sliced the CA API into a dedicated module.
The CA (mitm-ca) can be used in a RAM only fashion. feel free to take a look (by project is in very early stages, this is just for reference)

**Comment by Devhercule** [comment]
Thank you
