### ISSUE TITLE
Modify all chunks at once

### ISSUE THREAD

**Issue by ThauEx** [joeferner/node-http-mitm-proxy#15]
Hi,
is it possible to modify all chunks at once? The response is a big json document and to parse it, I need to get all chunks first. 
With the default https.request I could collect all chunks with the on data event and push all concated chunks in the on end event. I found the onResponseEnd event in the script, but I don't know how to return the combined chunks at once.

**Comment by felicienfrancois** [comment]
[Here is a example](https://github.com/joeferner/node-http-mitm-proxy/blob/master/test/processFullResponseBody.js) of how to achieve it (works since today thanks to this fix: https://github.com/joeferner/node-http-mitm-proxy/commit/0e40d2d550e3d815f6ef516086a34a256a398400

**Comment by felicienfrancois** [comment]
Could also be closed
