### ISSUE TITLE
WebSockets don't seem to be working

### ISSUE THREAD

**Issue by arasmussen** [joeferner/node-http-mitm-proxy#153]
I'm using node-http-mitm-proxy as a MITM proxy for my iOS device. It's successfully intercepting HTTP/HTTPS requests, but not WebSocket connections/events. The connections/events are successfully being proxied (the app works), but not intercepted by `onWebSocketConnection`, etc.

I can see the `WebSocket.Server` being created, with `{server: httpsServer}` passed in. This looks good, but then I added a `console.log` to `_onWebSocketServerConnect`, and it's never being called. I'm not sure why, I spent an hour or so trying to figure it out, but haven't come up with anything.

Any ideas? Thanks in advance, for this library, and your help on this issue. 😊

**Comment by arasmussen** [comment]
It looks like the problem may be that certain iOS traffic (like WebSockets) does not use the proxy specified in the Settings > Wi-Fi > HTTP Proxy Settings. Bummer...

**Comment by DevSidious** [comment]
What about **proxy.js, line 108** from master ?

`this._onWebSocketServerConnect.bind(this, true)`

Int this case, **this** is the WebSocket server and not the Proxy server, which spits out:

```
TypeError: Cannot read property 'bind' of undefined
```

Instead of the above, we need:

```
  var self = this;
  wssServer.on('connection', function(ws, req) {
      ws.upgradeReq = req;
      self._onWebSocketServerConnect.bind(self, true);
  });
```

However, even with this fix, it seems that none of the event handlers are being called. The following prints no web socket messages on the console:

```
'use strict';

var Proxy = require('http-mitm-proxy');
var proxy = Proxy();

proxy.onWebSocketConnection(function(ctx, callback) {
    console.log('WEBSOCKET CONNECT:', ctx.clientToProxyWebSocket.upgradeReq.url);
    return callback();
});

proxy.onWebSocketFrame(function(ctx, type, fromServer, message, flags, callback) {
    console.log('WEBSOCKET FRAME ' + type + ' received from ' + (fromServer ? 'server' : 'client'), ctx.clientToProxyWebSocket.upgradeReq.url, message);
    if (message) var hackedMessage = message.replace(/Rock it/ig, 'Hack it');
    return callback(null, message, flags);
});

proxy.onWebSocketError(function(ctx, err) {
    console.log('WEBSOCKET ERROR ', ctx.clientToProxyWebSocket.upgradeReq.url, err);
});

proxy.onWebSocketClose(function(ctx, code, message, callback) {
    console.log('WEBSOCKET CLOSED BY ' + (ctx.closedByServer ? 'SERVER' : 'CLIENT'), ctx.clientToProxyWebSocket.upgradeReq.url, code, message);
    callback(null, code, message);
});


proxy.listen({
    port: 8081,
    sslCaDir: "D:\\http-mitm-proxy",
    forceSNI: false
});
```

**Comment by arasmussen** [comment]
https://github.com/joeferner/node-http-mitm-proxy/pull/154

**Comment by DevSidious** [comment]
> It looks like the problem may be that certain iOS traffic (like WebSockets) does not use the proxy specified in the Settings > Wi-Fi > HTTP Proxy Settings. Bummer...

@arasmussen I just tested the websockets on an iPad (iOS 10.3.3) with Safari and Firefox. Everything works as expected, however it might be different for apps. Are you still facing this inconvenient?

**Comment by arasmussen** [comment]
@DevSidious Yeah I think native iOS app WebSocket traffic doesn't use the Wi-Fi proxy you specify, for some reason. Maybe because the ports are non-standard and Apple worries that the proxy won't properly proxy them? Just a guess.

See https://blog.netspi.com/intercepting-native-ios-application-traffic/.

Even after my pull request, I'm still not intercepting native iOS WebSocket traffic.

**Comment by DevSidious** [comment]
@arasmussen I'm unfamiliar with the details of your setup, however apps use certificate pinning for secure connections which prevents MITM. 

If that's a secure WebSocket (WSS), the certificate pinning might prevent the proxy from actually proxying the websocket. I gues some WireShirking might shed some light into what's going on.
