### ISSUE TITLE
read ECONNRESET without keepAlive

### ISSUE THREAD

**Issue by freewil** [joeferner/node-http-mitm-proxy#177]
I've been playing around with proxying https traffic and it appears to mostly work just fine. Though, I will always get an `ECONNRESET` error, unless enabling `keepAlive`. It appears `http-mitm-proxy` is somehow attempting to read from the socket after the response ends and enabling `keepAlive` appears to mitigate this issue.

I'm using the latest LTS version of Node, v10.14.2, latest master of `http-mitmproxy` (954f45669d561f58a5e081555c19c9336cbb2077). This error also occurs on versions prior to Node v10.0.0, as I've tried it with both v9 and v8, although it occurs silently since there is no error handler for it within my example code or `http-mitm-proxy`. It seems there was a change starting with Node v10.0.0 where the error is thrown unless an event handler for `error` is added on a socket.

## proxy.js
```js
"use strict";

const Proxy = require("http-mitm-proxy");

const proxy = Proxy();

proxy.onError((ctx, err) => {
  console.error("Proxy error", err);
});

proxy.listen({ host: "localhost", port: 3128, keepAlive: !!process.env.PROXY_USE_KEEPALIVE });
```

## https test request
```bash
$ curl -vvv \
  --proxy-insecure \
  --insecure \
  --include \
  --ipv4 \
  --http1.1 \
  --proxy http://localhost:3128 \
  https://raw.githubusercontent.com/joeferner/node-http-mitm-proxy/722c07f301454537db5a47d593edc2ffc1bfd7cf/.travis.yml
```

## Output without `keepAlive` (error)
```bash
$ node proxy.js
starting server for raw.githubusercontent.com
https server started for raw.githubusercontent.com on 60903
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at Socket.onerror (_stream_readable.js:690:12)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

## Output with `keepAlive` (no error)
```bash
$ PROXY_USE_KEEPALIVE=1 node proxy.js
starting server for raw.githubusercontent.com
https server started for raw.githubusercontent.com on 61179

```

**Comment by DenisKrsk** [comment]
I have the same problem in node-v10.15.0-x64. keepAlive: true did not help

**Comment by bjowes** [comment]
The suggested fix by @freewil worked for me, please merge it to official version.

**Comment by XuluWarrior** [comment]
Using keepAlive seems to reduce the ECONNRESET but they still happen and bring the server down.

https://github.com/hellodigit/node-http-mitm-proxy/commit/2a2253cc3a44dee377029dbef25c1bea2b4cf995 fixes the crashing behaviour. 

Can you create PR and hopefully get it merged?

**Comment by bjowes** [comment]
@XuluWarrior , I have created a PR.

**Comment by XuluWarrior** [comment]
@bjowes 
Great!
