### ISSUE TITLE
ENOTFOUND error -- how to catch?

### ISSUE THREAD

**Issue by vonGameTheory** [joeferner/node-http-mitm-proxy#18]
Trying to figure out how to catch an ENOTFOUND error (from request made to the proxy using  URL with a non-existent host that fails dns lookup) or similar request level errors -- they become uncaught exceptions and crash the process.  Of course I can use 

process.on('uncaughtException', function(err) ...

but that doesn't really help respond to bad request (it isn't tied to specific request) and leaves the process in an unstable state.  I'm just not experienced enough with node to figure this out.  (Simply avoiding bad requests is impossible as many come from secondary requests from a site, for instance it may link to a .css file on a non-existent host.)

**Comment by jacopofar** [comment]
I found a solution that is a bit ugly but works for me:

```
var dns = require('dns');

proxy.onRequest(function(ctx, proxy_callback) {

  console.log("visiting "+ctx.clientToProxyRequest.headers.host+ctx.clientToProxyRequest.url);
  
dns.lookup(ctx.clientToProxyRequest.headers.host,function(domain_error){
    if(domain_error){
      console.log(" WARNING: domain not found: "+ctx.clientToProxyRequest.headers.host);
      return proxy_callback("failed DNS lookup for domain '"+ctx.clientToProxyRequest.headers.host+"'");
    }
    return proxy_callback();
  });
```

so I check the domain beforehand and in case of error block the request. Trying it I didn't notice performance problems, but still the browser, not receiving a response, shows it as pending instead of showing an error.

If you know how to give back an error from the proxy that would be nice.

**Comment by vonGameTheory** [comment]
Yes, I came up with something similar that works for this particular error (dns failure).  And then I realized like you that I didn't know how to abort a request and change the response to a 404 or whatever for the browser so it isn't hanging until it times out.  However, it is easy enough to redirect the request.  So if you catch a bad host, just change it:

req.proxyToServerRequestOptions.host = '127.0.0.1';
req.proxyToServerRequestOptions.port = 7126;

and then let the request continue.

In the same script that is running the proxy server, I set up a second simple local server at port 7126 that responds to any request with a 404 error.  And so the request is completed and the 404 is sent back to the browser.  (Of course you could make it a little fancier to your needs.)


So that's kludgy, but it works for the ENOTFOUND dns errors.  HOWEVER, the larger issue remains as there are a few more possible errors of this type that I still don't know how to catch.  One that I've run into also is ECONNREFUSED, where the host is good but the server is just down or something and not responding.  Again you need to use "uncaughtException" and the request hangs.  Of course you could do something similar as with dns, but now you'd actually have to make the request  unproxied just to see if it works, which kinda defeats the whole purpose of the proxy.

I've seen other examples of catching these errors in node, but they are at the level of http.request, and I can't figure out how to do that in the context of this proxy.  (And the other proxies I looked at were so complicated otherwise -- this one does just what I want except for catching these rare errors that cause hangs.)

**Comment by felicienfrancois** [comment]
The best way is to catch `error` event on ctx.proxyToServerRequest:
I don't think it could be done with the current available events.

I will do a PR soon to add an `onRequestError` handler that would default to send a 504 error to the client.

**Comment by felicienfrancois** [comment]
Now thoose error are catched and sent to onError handler.
You can send a custom response to the client using this handler.
By default it send a HTTP 504 Error - Proxy Error with the error message in the body.

**Comment by vonGameTheory** [comment]
Great, thanks!

**Comment by felicienfrancois** [comment]
I think this issue could be close now

**Comment by vonGameTheory** [comment]
I have found a few still that it does not catch and go to the generic "uncaught exception", but they are happening when the response is in progress rather than at the request level.  ECONNRESET is one, which might happen if the remote server abruptly stops.  But the end result is the same -- you are left with a hanging request where nothing gets sent back to the client and then it just times out eventually.  Is there something we can attach to the response side of things so we catch all of them?

**Comment by felicienfrancois** [comment]
@vonGameTheory can you provide details of the uncaught exception you get ?
A stack trace (or better a https://github.com/mattinsler/longjohn stack trace) would be appreciated.

It's not easy to catch all errors, as they are asynchronous and cannot be catched with `try { } catch`. The only way is to add error event handlers on all request/response/socket, what I though done

**Comment by vonGameTheory** [comment]
Yes, I will see if I can generate some myself in a repeatable way using my own servers.  So far it has just been random stuff through real servers out in the world that haven't been very predictable.

**Comment by felicienfrancois** [comment]
@vonGameTheory can you tell me if you still get uncatched errors with latest release 0.2.0 ?

**Comment by vonGameTheory** [comment]
I will give it a try.

**Comment by vonGameTheory** [comment]
I see it catching some errors it was not.  Going to try to throw it all the bad and aborted requests I can find. Busy time right now though.

I also see someone made it so it makes proper serial#'s for the certs it generates.  Thanks for that, I was going to bring that up as I had worked up a quick hack for that so the browser wouldn't throw errors about it.  The proxy seems to now work fully in any browser on https pages without error if you import and trust the root cert that it makes.  Normally I don't use with regular browser, but very helpful for testing...

**Comment by felicienfrancois** [comment]
I think there are no longer uncatched errors => closing
