### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by felicienfrancois** [joeferner/node-http-mitm-proxy#20]
I was wondering why this cool project is not published to npm.
Is it a choice?

You can publish it to npm by creating an account on npmjs.org and then executing the following command at the root of the project:
```
npm login
# then enter your login and passwod
npm publish
```

**Comment by jacopofar** [comment]
+1 would be nice

**Comment by joeferner** [comment]
published v0.0.1

**Comment by felicienfrancois** [comment]
@joeferner you're awesome, thank you!
this module is the first mitm proxy module working with https out of the box.
