### ISSUE TITLE
Callback is not a function. Line 97:lib/proxy.js

### ISSUE THREAD

**Issue by jdcoding01** [joeferner/node-http-mitm-proxy#205]
After executing example, google.com MITM test, I get returned an error: 

TypeError: Callback is not a function at Server.self.httpServer.listen(lib/proxy.js) (line 97)

**Comment by samuil4** [comment]
I got the same error.

**Comment by sliterok** [comment]
You could update to newer version, or add a callback to .listen as such:
```
proxy.listen({
	port: 8081
}, e => {
    console.log('proxy listening')
});
```

**Comment by atwright147** [comment]
So does that mean all of the documentation and examples are wrong?
