### ISSUE TITLE
Requirements for trusted certificates new Catalina iOS13

### ISSUE THREAD

**Issue by Usernameisalreadytaken5** [joeferner/node-http-mitm-proxy#208]
My cert get ignored maybe because is valid until 2026 in iOS 13 and macOS 10.15 ( Catalina ) mitm

All TLS server certificates must comply with these new security requirements in iOS 13 and macOS 10.15:

> TLS server certificates and issuing CAs using RSA keys must use key sizes greater than or equal to 2048 bits. Certificates using RSA key sizes smaller than 2048 bits are no longer trusted for TLS.

> TLS server certificates and issuing CAs must use a hash algorithm from the SHA-2 family in the signature algorithm. SHA-1 signed certificates are no longer trusted for TLS.

> TLS server certificates must present the DNS name of the server in the Subject Alternative Name extension of the certificate. DNS names in the CommonName of a certificate are no longer trusted.

> **TLS server certificates must have a validity period of 825 days or fewer (as expressed in the NotBefore and NotAfter fields of the certificate).**

Similar issue:
https://github.com/symfony/cli/issues/146

**Comment by noonat** [comment]
I also ran into this on iOS 13. It seemed like validity period was the only thing node-http-mitm-proxy was violating. I don't have a Catalina install to test on, but reducing the validity period made things work for me on iOS 13. I've opened a pull request with that change.
