### ISSUE TITLE
How can i modify the headers??

### ISSUE THREAD

**Issue by impraveenbhadauriya** [joeferner/node-http-mitm-proxy#219]
I want to change few response and request headers, how can i do it??

I tried to change but didn't reflected on the browser

proxy.onResponseEnd(function (ctx, callback) {
    ctx.proxyToClientResponse._header["cache-control"] = "no-cache";
    return callback();
});

**Comment by TheGreatRambler** [comment]
How did you fix this?

**Comment by TheGreatRambler** [comment]
The error was actually unrelated to this issue, nvm.
