### ISSUE TITLE
v0.10.0 does not contain javascript files

### ISSUE THREAD

**Issue by johenning** [joeferner/node-http-mitm-proxy#273]
I can't get version [0.10.0 from npm](https://www.npmjs.com/package/http-mitm-proxy/v/0.10.0) to work. I suspect the issue is not with me, but that a broken version was released?

There are no `.js` files in the package, looks like it was not actually compiled before release? (Or it was compiled, but since `noEmit` is set no files were generated).
This might work for TypeScript projects, but as far as I can see plain JavaScript is still supported?

**Comment by joeferner** [comment]
Can you give 0.10.1 a try.  I think this commit should have fixed it... https://github.com/joeferner/node-http-mitm-proxy/commit/73931cf84af431587ec2cdedfd15e68b2cb8ac3f

**Comment by johenning** [comment]
Back to working for me, thanks

**Comment by johenning** [comment]
Actually, no. My typescript unit-tests worked, but the component doesn't actually start.

Here is the error I get when I try the [example](https://www.npmjs.com/package/http-mitm-proxy):
```bash
$ npm install http-mitm-proxy
$ node
Welcome to Node.js v16.18.0.
Type ".help" for more information.
> var Proxy = require('http-mitm-proxy');
Uncaught:
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/jhenning/node_modules/http-mitm-proxy/dist/index.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/jhenning/node_modules/http-mitm-proxy/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at __node_internal_captureLargerStackTrace (node:internal/errors:478:5)
    at new NodeError (node:internal/errors:387:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1182:19)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by joeferner** [comment]
OK, I think it should now be working 0.10.2. I tried it locally with success.

**Comment by johenning** [comment]
Yes, it works now. Though its missing the dependency to `uuid` in the package.json, which one thus has to install manually
