### ISSUE TITLE
Fresh Install - TypeError: Proxy is not a function

### ISSUE THREAD

**Issue by leiske** [joeferner/node-http-mitm-proxy#275]
Hi. 

## Issue

When running `npm install --save http-mitm-proxy` and attempting to run the example code I get:
```
const proxy = Proxy();
              ^

TypeError: Proxy is not a function
```

I've tried using the extension `js`, `mjs` and switching to `import Proxy from 'http-mitm-proxy`. I tried to downgrade versions with no luck. Not sure if I'm doing anything wrong and didn't see any issues mentioning this. Apologies if I've missed something pretty basic.

I also saw in the Examples you use `new Proxy`, but I receive `Proxy is not a constructor` unfortunately.

When adding `console.log({ Proxy });` after the import I receive this:
```js
{
  Proxy: { default: [class Proxy] { wildcard: [Object], gunzip: [Object] } }
}
```

Switching to `const Proxy = new Proxy.default()` yields no error, but wanted to raise this `default` issue regardless.

More than happy to try things out and/or provide more information. Thank you.

### Information

OS: Windows 10, 19045.2486
Node Versions: 14.21.2, 16.19.0 (sidenote - node 12 is not supported because optional chaining is used [here](https://github.com/joeferner/node-http-mitm-proxy/blob/master/lib/middleware/gunzip.ts#L8). Consider updating the README?)
`http-mitm-proxy` versions: 10.1, 10.2

### Repro Code
```js
var Proxy = require('http-mitm-proxy');
var proxy = Proxy();

proxy.onError(function(ctx, err) {
  console.error('proxy error:', err);
});

proxy.onRequest(function(ctx, callback) {
  if (ctx.clientToProxyRequest.headers.host == 'www.google.com'
    && ctx.clientToProxyRequest.url.indexOf('/search') == 0) {
    ctx.use(Proxy.gunzip);

    ctx.onResponseData(function(ctx, chunk, callback) {
      chunk = new Buffer(chunk.toString().replace(/<h3.*?<\/h3>/g, '<h3>Pwned!</h3>'));
      return callback(null, chunk);
    });
  }
  return callback();
});

proxy.listen({port: 8081});
```

**Comment by joeferner** [comment]
I updated the version (1.0.0) and readme with the fix. `Proxy` was being exported as default, this is now updated.
