### ISSUE TITLE
support to proxy chain

### ISSUE THREAD

**Issue by wisec** [joeferner/node-http-mitm-proxy#40]
I didn't find a way to set a proxy in  mitm-proxy to have multiple proxies chain.
Something like

 Browser -> Node-Http-Mitm-Proxy -> Internal Squid Proxy -> Internet

Is there any workaround?

**Comment by felicienfrancois** [comment]
The workaround is to set the agent to use for the request to the server
```
proxy.onRequest(function(ctx, cb) {
    ctx.proxyToServerRequestOptions.agent = proxyAgent;
});
```

You can create the proxyAgent using one of the agent implementation available on npmjs:
https://www.npmjs.com/search?q=proxy+agent

**Comment by mbrechet** [comment]
Hi, I've tried to use agent implementation but some proxy prevent CONNECT method on it, is there a way to just forward the original request to the proxy ?

**Comment by felicienfrancois** [comment]
I think CONNECT method is required for SSL through a proxy.
Even without node-http-mitm-proxy, you may not be able to browse an https website with your squid setup.
You should enable it in Squid
http://www.linuxquestions.org/questions/linux-networking-3/connect-method-is-not-allowed-when-using-squid-transparent-proxy-809047/

**Comment by mbrechet** [comment]
hi @felicienfrancois thanks for your answer.

My problem occurs behind a crop. porxy so I can't interract directly with it.

To bypass the problem I use [request](url) library.

**Comment by felicienfrancois** [comment]
OK. Thank you for your feedback.
https://github.com/request/request module handle proxy with this agent: https://github.com/request/tunnel-agent

So setting the agent to such this one may works too ...

**Comment by mbrechet** [comment]
Ho, thanks

I'll try it, I'think it's the solution to support proxy chain

Thanks for your help

Regards

mbrechet
