### ISSUE TITLE
serverToProxyResponse is an IncommingMessage and not a ServerResponse

### ISSUE THREAD

**Issue by kdzwinel** [joeferner/node-http-mitm-proxy#42]
According to the [documentation](https://github.com/joeferner/node-http-mitm-proxy#context) serverToProxyResponse should be a ServerResponse, as far as I can see it's an IncommingMessage instead. My guess is that it's a documentation bug?

P.S. This project rocks, thank you!

**Comment by felicienfrancois** [comment]
Yes this was documentation bug.
Fixed with commit https://github.com/joeferner/node-http-mitm-proxy/commit/681f1c611d7eae03903983103df80790a56c90bb
