### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by wisec** [joeferner/node-http-mitm-proxy#60]
Hello, 
when we have self signed certificates, the proxy does triggers an error. 
curl -x 127.0.0.1:8082 https://127.0.0.1 -ki
HTTP/1.1 200 OK

HTTP/1.1 504 Proxy Error
Date: Mon, 22 Feb 2016 20:41:20 GMT
Connection: keep-alive
Transfer-Encoding: chunked

PROXY_TO_SERVER_REQUEST_ERROR: Error: unable to verify the first certificate

I resolved using:
NODE_TLS_REJECT_UNAUTHORIZED=0 node myproxy.js

```
 //myproxy.js
Proxy().listen({port: 8082});
```
 
but I think It would be nice:
1. Since it's a proxy, to allow self signed certs to go through by default.
2. to have some way to easily set this option to true or false from the code. 

Am I missing something?
Thanks and keep up the great work!

**Comment by felicienfrancois** [comment]
You're talking about navigating on a server with a self signed certificate, right?
client (i.e. browser) <-> Proxy <-> Server (i.e. website)

There are 2 solutions to this issue:
1°) Global
Setting the environment variable `NODE_TLS_REJECT_UNAUTHORIZED` to 0, either from the command line like you did or in the code:
```javascript
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```
This is a global solution which disable SSL security checks for all https requests made from the whole app (not only from the proxy)

2°) Per request

```javascript
proxy.onRequest(function(ctx, callback) {
    ctx.proxyToServerRequestOptions.rejectUnauthorized = false;
});
```
This may do the trick (not tested)

I'm not sure changing the default behavior or adding a setting is needed. Maybe just a note in the documentation would be enough?

Feel free to make a pull request

**Comment by wisec** [comment]
@felicienfrancois thanks for your reply, actually number 2 is what I was looking for !

As you mentioned a note in the documentation would be really helpful.

Thanks
