### ISSUE TITLE
Usage question.

### ISSUE THREAD

**Issue by neeksor** [joeferner/node-http-mitm-proxy#72]
Thank you for making such great software available. I would like to intercept requests for a single domain and url and cause the request to be proxied to a different remote host. I've gotten as far as matching the request and sending a different response from the proxy to the client but that's it.

**Comment by felicienfrancois** [comment]
The easiest way to achieve what you want is:
```
proxy.onRequest(function(ctx, callback) {
  if (ctx.clientToProxyRequest.headers.host == 'www.youdomain.com'
    && ctx.clientToProxyRequest.url.indexOf('/base/url/to/intercept') == 0) {
    ctx.proxyToServerRequestOptions.host = 'www.overridehost.com';
    ctx.proxyToServerRequestOptions.path = '/override/url';
  }
  return callback();
});
```

So you'll let the proxy make the request to the server and transmit the response to the client.

`ctx.proxyToServerRequestOptions` is the options the proxy uses to make the request to the server.

**Comment by neeksor** [comment]
Hello,
Thank you for responding. I just figured it out and was going to post what I found here.
Thanks again!

**Comment by neeksor** [comment]
Would it be possible to apply the same process to a websocket connection?

I attempted the following:

```
proxy.onWebSocketConnection(function(ctx,callback) {
  if (ctx.clientToProxyWebSocket.upgradeReq.headers.host == 'www.mydomain.com'
    && ctx.clientToProxyWebSocket.upgradeReq.url.indexOf('/socket') == 0) {
    ctx.proxyToServerWebSocketOptions.url = 'ws://otherhost:port' + ctx.clientToProxyWebSocket.upgradeReq.url;
    ctx.proxyToServerWebSocketOptions.host = 'otherhost:port'
  }
  return callback();
});  
```
I see the proxy receiving the request and changing the proxyToServerWebSocketOptions.url and host properly. The websocket stays in the 'pending' state and never completes the connection.

**Comment by felicienfrancois** [comment]
did you try with only
```
ctx.proxyToServerWebSocketOptions.url = 'ws://otherhost:port' + ctx.clientToProxyWebSocket.upgradeReq.url;
```
without setting the host attribute ?

Also are you sure your target server support websockets on this path ?
You can also check headers (just print the whole ctx.proxyToServerWebSocketOptions to console)

**Comment by neeksor** [comment]
I tried just setting the url. The new target server receives the request and responds but it seems that the handshake never completes. 
In ctx.proxyToServerWebSocket.res.IncomingMessage , I saw the headers that came back from the new target server.

```
complete: true,
                 headers: 
                  { upgrade: 'websocket',
                    connection: 'Upgrade',
                    'sec-websocket-accept': '4R+HYL2y/RdRHttMm/pc0cGNpmw=',
                    'sec-websocket-extensions': 'permessage-deflate' },
                 rawHeaders: 
                  [ 'Upgrade',
                    'websocket',
                    'Connection',
                    'Upgrade',
                    'Sec-WebSocket-Accept',
                    '4R+HYL2y/RdRHttMm/pc0cGNpmw=',
                    'Sec-WebSocket-Extensions',
                    'permessage-deflate' ],
                 trailers: {},
                 rawTrailers: [],
                 upgrade: true,
                 url: '',
                 method: null,
                 statusCode: 101,
                 statusMessage: 'Switching Protocols',
```

**Comment by neeksor** [comment]
I found the issue.. The proxied request was requesting an invalid namespace from the websocket server.. Thanks again for your help. :+1:
