### ISSUE TITLE
HTTPS + Curl fails

### ISSUE THREAD

**Issue by BenHall** [joeferner/node-http-mitm-proxy#75]
Given the following command: `curl -i -x https://localhost:3001 https://www.google.co.uk/`

After launching the server, I'm first getting a response of `Server aborted the SSL handshake`

The next response is `Unknown SSL protocol error in connection`

The server is outputting `HTTPS_CLIENT_ERROR on : [Error: TLS handshake timeout]`

I've added the ca.pem into my OSX keychain.

When using a different command line tool, I get `HTTPS_CLIENT_ERROR on : [Error: 19282344:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/s3_pkt.c:1472:SSL alert number 42
19282344:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1210`

The server is based on your example. Any way to resolve this?

**Comment by felicienfrancois** [comment]
The proxy is an HTTP proxy which proxy both http and https trafic.
The proxy url should be __http__://localhost:3001 instead of __https__://localhost:3001

```
curl -i -x http://localhost:3001 https://www.google.co.uk/
```

**Comment by BenHall** [comment]
of course, sorry
