### ISSUE TITLE
Documentation gap?

### ISSUE THREAD

**Issue by deanshelton913** [joeferner/node-http-mitm-proxy#76]
Installed the ca.pem file, trusted it. but connecting to a running example proxy raises
`HTTPS_CLIENT_ERROR on : [Error: 140735258857472:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../deps/openssl/openssl/ssl/s3_pkt.c:1472:SSL alert number 48`

This is likely because i am doing something wrong, but i am having a hard time understanding what i am missing by looking at the readme.

**Comment by deanshelton913** [comment]
NOPE. I just needed to tell FIREFOX to trust the cert. I had added it to my mac keychain, thinking that was sufficient.  Bottom line: I am an idiot. Thank you for making an awesome project

**Comment by felicienfrancois** [comment]
@deanshelton913 you're not an idiot. Firefox is the only browser that uses its own certificate store instead of using OS one.

Adding a notice about how to setup the certificate on all OS and browsers is a good idea.
PR welcome :)
