### ISSUE TITLE
ssl handshake failure

### ISSUE THREAD

**Issue by kdzwinel** [joeferner/node-http-mitm-proxy#77]
I'm seeing a lot of these errors thrown when intercepting HTTPS traffic: 

> Error: 140735158005760:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:1472:SSL alert number 48
140735158005760:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:1210:

I'm able to reproduce it on node 4.1.1 and 5.1.1 for multiple hosts.

**Comment by felicienfrancois** [comment]
node-http-mitm-proxy is a mitm proxy which forge certificates for each browsed domains to be able to intercept the encrypted traffic.
Thoose certificates are forged with a self generated Certificate Authority which is obviously not trusted by OS and browsers.
As a result, when using the proxy with a browser/OS that have not been set up to either trust this Certificate Authority or ignore ssl errors, you get SSL handshake failures with "unknown ca" reason. Depending on the browser and the website, it will also show you a warning or even prevent you from browsing.

To fix this, you may either:
1°) Trust the Certificate Authority in your OS/Browser.
  - The Certificate is locate by default in `.http-mitm-proxy/certs/ca.pem` (relative to process.cwd())
  - On OSX, You can trust it in the keychain manager
  - On Windows, You can trust it in the internet settings (Content tab)
  - Unlike other browsers, Firefox have its own CA Store. You can trust the CA in Firefox Settings > Advanced > Certificates
2°) Ignore ssl errors in the browser (there are settings or command line parameters to do so in some browsers)
3°) Ignore HTTPS_CLIENT_ERROR error logs reporting in the proxy
```
proxy.onError(function(ctx, err, errorKind) {
  if (errorKind !== 'HTTPS_CLIENT_ERROR') {
    console.error(err);
  }
});

**Comment by kdzwinel** [comment]
Hey Félicien! Thank you for a detailed answer. I have added the `ca.pem` to my trusted certificates via keychain app. It works just fine with traffic coming from Chrome, Steam and couple others. It fails for some native apps (e.g. iTunes and App Store). Maybe the issue is that I added the certificate to the login keychain instead of System keychain? I'll test and get back to you.

**Comment by felicienfrancois** [comment]
@kdzwinel you're probably right. Apps that run as a different user than yours may requires the CA to be trusted by System keychain

**Comment by tgsoverly** [comment]
Has anyone installed the cert in iOS?  I added the ca.pem to iOS profile and it says trusted, but I am still getting this error.  Anyone have any experience?

**Comment by kics223w1** [comment]
- HI @felicienfrancois, my case is to determine which URL is fail when the proxy raise error `HTTPS_CLIENT_ERROR`, but the `ctx` is always null when the error is raised. I have digged into the library but end up nothing. 
 - Do you have a workaround for this case, or any other function to listen when the error `HTTPS_CLIENT_ERROR` is raised.
 - Note that: `ctx.onError` won't work due to `ctx` is null
 - Thank you in advance
