### ISSUE TITLE
How to tunnel https directly ? 

### ISSUE THREAD

**Issue by switer** [joeferner/node-http-mitm-proxy#86]
**http-mitm-proxy** without "`onConnect`" exposing, how can I tunnel https directly without create httpsServer ?

In some case,  proxy https request doesn't need  decrypting : )

**Comment by felicienfrancois** [comment]
There is a discussion about this on #50.

TLDR:
- This may be possible per hostname
- Pull request are welcomed

**Comment by felicienfrancois** [comment]
I have updated the title and the trailing comments of #50 

I think the discussion can now continue on #50.
=> Closing
