### ISSUE TITLE
dependencies: insecure

### ISSUE THREAD

**Issue by DannyiCracked** [joeferner/node-http-mitm-proxy#92]
https://www.npmjs.com/package/http-mitm-proxy

Your package has a low search / page rank (couldn't find it on top google hits even using the search term `http-mitm-proxy npm`)

You should update your `package.json` to use `ws@^1.1.1`. 

https://www.npmjs.com/package/ws

**Comment by joeferner** [comment]
thanks, done: cb384b0f5b40e28ff422c4c0d145419382c21e41
