### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by goldsteindavid** [joeferner/node-http-mitm-proxy#93]
When I install with the command line:
npm install --save http-mitm-proxy
I get the following message and the install stops:
npm WARN install Refusing to install http-mitm-proxy as a dependency of itself

**Comment by felicienfrancois** [comment]
`npm install --save http-mitm-proxy` means _install http-mitm-proxy as a dependency of current project/directory_
 `npm install` means _install all dependencies of current project/directory_

So to install http-mitm-proxy as a dependency of a nodejs project, you should go to the root of the project and exec `npm install --save http-mitm-proxy`
__BUT__ to use http-mitm-proxy in a standalone way you should either
- clone/download the repo content, cd into the http-mitm-proxy directory and exec `npm install`

or
- exec `npm install -g` (or `npm install --global`) anywhere to install it globally. You should then be able to execute the `http-mitm-proxy` command in a command prompt
