### ISSUE TITLE
Not intercepting

### ISSUE THREAD

**Issue by nodkrot** [joeferner/node-http-mitm-proxy#95]
Here is the code

``` js
var Proxy = require('http-mitm-proxy');
var proxy = Proxy();

proxy.onError(function(ctx, err) {
    console.error('proxy error:', err);
});

proxy.onRequest(function(ctx, callback) {
    console.log(ctx.clientToProxyRequest.headers.host)

    return callback();
});

proxy.listen({
    port: 8080
});
```

Im starting my server `node index.js` and refreshing google.com and dont see any console logging?

**Comment by felicienfrancois** [comment]
You have to setup your browser or OS to use the proxy.

**Comment by hkors** [comment]
It didn't work for me as well, until I discovered I was blocking application "Node.js: Server-side JavaScript" in Windows Firewall. Maybe your firewall is blocking your proxy as well... And I assume you've opened port 8080.
