### ISSUE TITLE
need ca.crt for some androids (not ca.pem)

### ISSUE THREAD

**Issue by l3iggs** [joeferner/node-http-mitm-proxy#96]
The `ca.pem` provided here does not work for my android (n). I can get it to work by generating a `ca.crt` from your `ca.pem` like so:
```
openssl x509 -inform PEM -outform DM -in .http-mitm-proxy/certs/ca.pem -out .http-mitm-proxy/certs/ca.crt
```
but this requires the openssl binary which may not always be easy to come by. Could the project here directly generate the `ca.crt` that many of us need?
see: https://github.com/justinleewells/pogo-optimizer/pull/108

**Comment by felicienfrancois** [comment]
We use node-forge (pure js) to generate the certificate.
You can use node-forge to convert the pem certificate into a crt certificate:
```javascript
var fs = require('fs');
var forge = require('node-forge');
var cert = forge.pki.certificateFromPem(fs.readFile('.http-mitm-proxy/certs/ca.pem'));
fs.writeFile('.http-mitm-proxy/certs/ca.crt', forge.asn1.toDer(forge.pki.certificateToAsn1(cert)).getBytes(), {encoding: 'binary'});
```

**Comment by felicienfrancois** [comment]
Also, if you want to pre-generate the ca certificate files to avoid the `sleep 10` hack, you can have a look at https://github.com/joeferner/node-http-mitm-proxy/blob/master/lib/ca.js#L145

**Comment by l3iggs** [comment]
@felicienfrancois Thanks very much!

**Comment by saikrishna321** [comment]
@felicienfrancois I tried the above for android and I always see no-internet connection in my phone. Can you point me to any docs on how to setup for android/ios devices?
