### ISSUE TITLE
Question: Need .p12 certificate

### ISSUE THREAD

**Issue by Vortelf** [joeferner/node-http-mitm-proxy#98]
Is there any way to generate .p12 certificate bundle to work with Windows?

**Comment by felicienfrancois** [comment]
> Is there any way to generate .p12 certificate bundle

Yes, you can use either openssl or [node-forge](https://github.com/digitalbazaar/forge#pkcs12) (for pure node solution) to convert the certificate file to pk12.

> to work with Windows

??? The PEM Format works with Windows:
- Go to Control Panel > Internet Settings > Content > Certificates > Trusted Root Certificate Authorities > Import
- Select the ca.pem file from certs directory
