### ISSUE TITLE
forged certificate from date can be out of range due to clock skew.

### ISSUE THREAD

**Issue by matthewaveryusa** [joeferner/node-http-mitm-proxy#99]
When I MitM myself chrome stable returns quite a few errors due to the cert being outside the valid date range even though my clocks are synchronized between the machine that's acting as my proxy and my desktop. Adjusting the from date to 2 days back removed all the errors. The change is trivial and I'm not sure how far back you would want to go, so I'm just attaching the diff. Perhaps a better alternative would be to match the to/from date of the original cert? I can submit a pull request for either solution if there's interest.

Thanks,
-Matt

```
$ git diff
diff --git a/lib/ca.js b/lib/ca.js
index 4fb83c1..7345ba2 100644
--- a/lib/ca.js
+++ b/lib/ca.js
@@ -200,7 +200,8 @@ CA.prototype.generateServerCertificateKeys = function (hosts, cb) {
   var certServer = pki.createCertificate();
   certServer.publicKey = keysServer.publicKey;
   certServer.serialNumber = this.randomSerialNumber();
-  certServer.validity.notBefore = new Date();
+  var date = new Date();
+  certServer.validity.notBefore.setDate(date.getDate()-2);
   certServer.validity.notAfter = new Date();
   certServer.validity.notAfter.setFullYear(certServer.validity.notBefore.getFullYear() + 2);
   var attrsServer = ServerAttrs.slice(0);
```

**Comment by felicienfrancois** [comment]
Thank you for your change proposal.

I pushed the change to master #https://github.com/joeferner/node-http-mitm-proxy/commit/b92ebe68e4db04d3c8a21fd2ab82b7f1fc76aac4
